### ISSUE TITLE
Folders not being checked for correct case

### ISSUE THREAD

**Issue by kesne** [dcousineau/force-case-sensitivity-webpack-plugin#5]
It looks like this catches cases where the case of the filename differs, but it doesn't catch the case where the folder has a different case. So for example if you have `mysite/Text` and you do `require('MySite/Text')` it won't throw an error because the filename still has the same case, but it will still fail on case-sensitive OS's.

**Comment by Urthen** [comment]
I had the same requirement. Since this project doesn't seem to be in active development anymore, I partly rewrote it and released it here if you're interested: https://github.com/Urthen/case-sensitive-paths-webpack-plugin

Daniel, I included your original plugin and license in attribution. If you'd like me to make any changes to attribution, let me know.

**Comment by dcousineau** [comment]
@Urthen thanks! Sorry I kinda abandoned this for a while. I merged another PR that solved this problem using the glob module and it solves my/our needs. Attribution or no just glad people were able to solve while I was sleeping at the wheel  :/ 

@kesne Sorry I let this fall off the planet.

Updated to 0.2.0
